[[redirects]]
  from = "/fun"
  to = "https://hazardsof.fun"
  status = 200
  
[[redirects]]
  from = "/profile/*"
  status = 200
  conditions = {Role = ["*"]}
  # By default, redirects won't be applied if there's a file with the same
  # path as the one defined in the `from` property. Setting `force` to `true`
  # will make the redirect rule take precedence over any existing files.
  force = true

[[redirects]]
  from = "/profile/*"
  to = "/blog"
  status = 401
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
