
[build]
  functions = "functions/"
  ignore = "git diff --quiet HEAD^ HEAD"

[[redirects]]
  from = "/search"
  to = "https://something.netlify.app"
  status = 200
  force = true
  headers = {Host = "hazardsof.com"}

[[headers]]
  for = "/.netlify/functions/identity-signup"
  [headers.values]
    Netlify-Vary = "query=''"
