[context.build]
  publish = "src"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    strict-transport-security = "max-age=31536000; includeSubDomains"
    # Content-Security-Policy-Report-Only = "default-src https: 'unsafe-inline' 'unsafe-eval'"

# Basic redirect rules
redirects = [
  {from = "/platform/integration", to = "/discover/ehr-integrations"},
  {from = "/foo", to = "/discover/ehr-integrations"},
  {from = "/*", to = "/404/index.html", status = 404}]