on: 
  issues:
    types: [opened]

jobs:
  test-actions:
    runs-on: ubuntu-latest
    name: Send slack notification on new issues
    steps:
    - name: Slack notification action
      id: test
      uses: depadiernos/my-slack-action@v1.0.0
      with:
        slack-url: "${{ secrets.SLACK_WEBHOOK_URL }}"
