on: 
  issues:
    types: [opened]

jobs:
  test-actions:
    runs-on: ubuntu-latest
    name: Send slack notification on new issues
    steps:
    - name: Slack notification action
      id: test
      uses: depadiernos/my-slack-action@v1.2
#       with:
#         who-to-greet: 'Mona the Octocat'
#     # Use the output from the `test` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.test.outputs.time }}"
