on: 
  issues:
    types: [opened]

jobs:
  test-actions:
    runs-on: ubuntu-latest
    name: Send slack notification on new issues
    steps:
    - name: Slack notification action
      id: test
      uses: depadiernos/my-slack-action@v1.5
      with:
        slack-webhook-url: ${{secrets.SLACK_WEBHOOK>URL}}
