on: 
  issues:
    types: [opened]

jobs:
  test-actions:
    runs-on: ubuntu-latest
    name: Send slack notification on new issues
    steps:
    - name: Slack notification action
      id: test
      uses: depadiernos/my-slack-action@v1.8
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
